### ISSUE TITLE
GAE php5.5

### ISSUE THREAD

**Issue by nickypeh** [shpasser/GaeSupport#7]
Hi, 
I encounter a problem for the new Google App Engine runtime for the php 5.5 that supported Curl now. 
Previously, in PHP 5.4, everything is running fine for the development and production as well. 

After adjusted to PHP 5.5, it seems like the error logging is having some error. 
First, it seems like it cannot detect our environment using the 'hostname' where i have to explicit set it as follow : 

```
$env = $app->detectEnvironment(function(){
	  if (strpos($_SERVER['HTTP_HOST'],'.') === false) {  
	      return 'local';  
	  }
	  return 'production';
	});
```

However, with this, it could detect it is in local mode now but it will have this error now. 

**Error in exception handler: The stream or file "/GAE/server/app/storage/logs/laravel.log" could not be opened: failed to open stream: No such file or directory in /GAE/bookme/GAE/server/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84**

If i revert it back to 5.4 and everything works fine again. I also make sure my storage folder got all the read and write access. 
Any advise on this ? 

Thanks. 

Regards, 
Nick

**Comment by shpasser** [comment]
I think that the issue is fully related to the environment detection.
The only supported log handler for GAE is 'syslog'. According to the posted error message the log handler used is using files, and was configured using `app/start/local.php`. When running on GAE the `production` environment is supposed to active and  the log handler is configured using `app/start/production.php`, which configures log to use `syslog` handler. 

I managed to run my test app on GAE without applying any changes.

I would suggest to revert the `bootstrap/start.php` to the original coding:
```php
$env = $app->detectEnvironment(array(

	'local' => array('homestead'),

));
```
or something else, but using the same format i.e. `'env-name' => ['host1', 'host2', ...]`.

After that, please capture the error via GAE log and post it here for further discussion.

Best,

Ron.

**Comment by nickypeh** [comment]
Hi Ron, 
Just to make sure, you did try it on the **runtime:        php55** for the app.yaml right ? 

This is my ```bootstrap/start.php``` which I converted back to the original files

```php
$env = $app->detectEnvironment(array(
	'local' => array('Mac-mini.local'),
));
```

Some how. when i try to print out my monolog to get the current environment, it is still in production mode even though i set it to my local machine. I double check with my machine hostname to make sure it is not misspelled. Take note that it is working on php5.4 before the updates carried out by GAE. 

Please advise. 

Regards, 
Nick

**Comment by shpasser** [comment]
I used the following `app.yaml` file to push my app to GAE:
```yml
application:    test1-app
version:        1
runtime:        php55
api_version:    1

handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        - url: /packages
          static_dir: public/packages

        - url: /.*
          script: public/index.php

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\.(?!env\.php).*$
        - ^(.*/)?node_modules.*$
        - ^(.*/)?_ide_helper\.php$
```
and I'm using `homestead` (via vagrant) for my local environment.

Anyway I would suggest you run PHP code like this one:
```php
<?php 
var_dump(gethostname());
```
in order to obtain the correct hostname.

If you could send me a sample app code having the same issue I will be able to investigate.
In the mean time I would suggest to use `dd(var_name)`, while putting it in different places in the code to examine variables values. Another thing is to try creating a new Laravel 4 app, setup it for GAE and see if the issue reappears.

Best,

Ron.

**Comment by nickypeh** [comment]
Hi Ron, 
I tried with the simplest project but somehow the issue is reappearing.
I have created a repositories in github as follow for the sample app code in order to debug: 
https://github.com/nickypeh/gaelaravel55

The ```boostrap/start.php``` local files are using my PC hostname. I doublecheck again with the 

PHP Code 
```php
<?php 
var_dump(gethostname());
```  
and I am getting the same hostname.

Hence, I tried to switch between runtime 5.4 and 5.5 with the same settings and apparently, the 5.4 could detect my environment. For a further testing, I change the $env to wrong local name in the bootstrap/start.php in PHP 5.4 runtime and it could switch to production which means, the 5.4 is working as expected but not the PHP 5.5 runtime.

I have configure the route '/env' to printout the current environment. 
Please help to test it out and let me know your input on this.

Thanks. 

Nick

**Comment by shpasser** [comment]
Hi Nick,
Just finished deploying your app on GAE, I had to change the app-id in `app.yaml` and GCS bucket name in `php.ini` in order to make it work, please take a look:

http://test-sql-l4.appspot.com
http://test-sql-l4.appspot.com/env

From my perspective the `production` environment works Ok in both PHP5.5. and PHP5.4.

Then I changed the `bootstrap/start.php` to include `homestead` instead of `ARMSs-Mac-mini.local` as a local environment and tested your app on `homestead` VM and also using `dev_appserver.py` and could not see any errors.

In my opinion there should be something in the workflow that you are using preventing the app from working properly or maybe something about your assumptions regarding the app. Please send me the exact set of commands, behaviours, assumptions and outputs you have in your workflow (including the deployment command, like `appcfg.py update ./`), so I could try to pinpoint the issue.

Best,

Ron.

**Comment by nickypeh** [comment]
Hi Ron, 
I guess going into production is not getting me any problem as it will detect in production. 
For me, the concern is at the local environment. As it can't do logging and selecting db based on environment unless I manually change DB settings.
Did you try on ur pc without using the homestead VM but use the 'hostname' instead? 
My steps are quite easy. It would be great to send u the deployment command but I am just running the app folder locally using the GoogleAppEngineLauncher which I didnt use any of the deployment command at the terminal. 

There is only one thing I change from PHP5.4 to PHP5.5,

```yaml
application:    gaelaravelsql
version:        1
runtime:        php55   --> changing this from php to php55
api_version:    1

handlers:
        - url: /favicon\.ico
          static_files: public/favicon.ico
          upload: public/favicon\.ico

        - url: /packages
          static_dir: public/packages

        - url: /.*
          script: public/index.php

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\.(?!env\.php).*$
        - ^(.*/)?node_modules.*$
        - ^(.*/)?_ide_helper\.php$

```

Hence, I just relaunch the app using the GoogleAppEngineLauncher and use the '/env' route, and it just echo me back with production environment. 

To conclude from PHP5.4 to PHP5.5, only one changes made which is the app.yaml from php to php55. 
Nothing else is changed. Switching back to PHP5.4 by removing the '55' in the app.yaml and everything works fine for detecting environment. At PHP5.4, I could do logging in the ```storage/logs/laravel.log``` as well.
